channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cython
  - ipython
  - ipyparallel
  - ipywidgets
  - numpy
  - matplotlib
  - mpi4py
  - networkx
  - pandas
  - scikit-image
  - scikit-learn
  - sympy
  - pymc3==3.8
  - numpy==1.18.0
  - pandas==1.0.0
  - seaborn==0.9.1
  - statsmodels==0.11.0
  - arviz==0.11.0
  - scikit-learn==1.0
  - scipy==1.7.1
  - matplotlib==3.4.3
  - openpyxl==3.0.3
  - xlrd==1.2.0
  - theano==1.0.5 
